---
linters:
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  IdSelector:
    enabled: false
  NestingDepth:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorFormat:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  StringQuotes:
    enabled: false
